version: "3.9"

services:
  web:
    build: .
    command:
      sh -c "python manage.py makemigrations
        && python manage.py migrate
        && python manage.py loaddata fixtures/*.yaml
        && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/backend/
