version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env/development/database
      - .env/development/app
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - .env/development/db
