# Generated by Django 3.2.5 on 2021-08-08 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_s', models.CharField(max_length=30, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'ordering': ('title_s',),
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many', models.PositiveSmallIntegerField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cocktail_ingredients', to='ingredients.ingredient')),
            ],
            options={
                'verbose_name': 'Cocktail ingredient',
                'verbose_name_plural': 'Cocktail ingredients',
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name of cocktail')),
                ('slug', models.SlugField(db_index=False, verbose_name='Slug')),
                ('serve_in', models.CharField(max_length=30, verbose_name='Serve in')),
                ('garnish', models.CharField(max_length=30, verbose_name='Garnish')),
                ('how_to_make', models.TextField(verbose_name='How to make')),
                ('review', models.CharField(max_length=100, verbose_name='Review')),
                ('history', models.TextField(verbose_name='History')),
                ('nutrition', models.CharField(max_length=50, verbose_name='Nutrition')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cocktail_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktailingredient')),
                ('style', models.ManyToManyField(related_name='cocktails', to='cocktails.Style')),
            ],
            options={
                'verbose_name': 'cocktail',
                'verbose_name_plural': 'Cocktails',
                'ordering': ('name',),
                'unique_together': {('slug', 'name')},
            },
        ),
    ]
