# Generated by Django 3.2.5 on 2021-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='cocktail_ingredients',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_ingredients',
            field=models.ManyToManyField(to='cocktails.CocktailIngredient'),
        ),
    ]
