# Generated by Django 3.2.5 on 2021-08-18 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='bartender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bartender_cocktails', to=settings.AUTH_USER_MODEL),
        ),
    ]
