# Generated by Django 3.2.5 on 2021-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_alter_cocktail_bartender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='title_s',
            field=models.CharField(max_length=30, unique=True, verbose_name='Title'),
        ),
    ]
