# Generated by Django 3.2.5 on 2021-09-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_alter_style_title_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
